# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreationMap
                                 A QGIS plugin
 Density population map creation by region
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-12-18
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Althéa Feuillet
        email                : althea.feuillet@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtWidgets import  QMessageBox
from qgis.core import (QgsVectorLayer, QgsFeature)

class Centroides:
    @staticmethod
    def createCentroids(layer):
        """
        Crée une nouvelle couche de points représentant les centroïdes des entités de la couche d'entrée.

        :param layer: La couche d'entrée dont les centroïdes doivent être créés.
        :type layer: QgsVectorLayer

        :return: La nouvelle couche de points représentant les centroïdes.
        :rtype: QgsVectorLayer

        Crée une nouvelle couche en mémoire pour les centroïdes, itère sur les entités de la couche d'entrée, calcule le centroïde de chaque entité
        et ajoute une entité correspondante à la couche des centroïdes.
        """
        try:
            # Créer une nouvelle couche pour les centroïdes
            centroid_layer = QgsVectorLayer("Point", "centroids", "memory")
            centroid_layer.dataProvider().addAttributes(layer.fields())
            centroid_layer.updateFields()

            # Itérez sur les entités de la couche d'entrée
            for feature in layer.getFeatures():
                geom = feature.geometry()
                centroid = geom.centroid() # Calcul du centroïde
                centroid_feature = QgsFeature()
                centroid_feature.setGeometry(centroid)
                centroid_feature.setAttributes(feature.attributes())

                # Ajouter l'entité à la couche des centroïdes
                centroid_layer.dataProvider().addFeatures([centroid_feature])
                
            return centroid_layer

        except Exception as e:
            QMessageBox.critical(None, 'Erreur', f'Erreur lors de la création des centroïdes : {str(e)}')